name: Run dagger examples
on:
  pull_request: 
    
jobs:
  examples:
    name: Run examples 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      
      - name: Run
        uses: dagger/dagger-for-github@d913e70051faf3b907d4dd96ef1161083c88c644
        with:
          version: "latest"
          verb: call
          module: ./tests
          args: all
